k和kr
hdcola/chstockbot pull request #16
Opened 2021-05-30 13:48 UTC by stephenzhu01

2021-05-30 14:54 UTC, hdcola commented on config.py
> +    CONFIG.setdefault("Token","1705438123:AAH0YE9hsOikJ1y4P72pHXyQMPYSzYPkQxU")       #BotToken
哈哈哈，你的token暴露啦～我要用来做坏坏的事情啦

2021-06-06 11:25 UTC, hdcola requested changes
改进的是思考部分。但是sendxyh.py少了发送消息的功能。

2021-06-06 11:25 UTC, hdcola commented on bot.py
> +    # commands += sendxyh.add_dispatcher(dispatcher)
怎么注释掉啦？

2021-06-06 11:25 UTC, hdcola commented on cmdproc/reportcmd.py
>              vio_text = "非文本信息" #若被举报信息不含文本则定义举报内容为非文本信息
如果非文本信息，应该会有好的解决方案，这个我建一个issue https://github.com/HDCodePractice/chstockbot/issues/15

2021-06-06 11:25 UTC, hdcola commented on cmdproc/reportcmd.py
> +        bot.unban_chat_member(groups[0],spammerId)
感觉这个应该有一个配置是否在/k或 /kr时同时 ban掉对应的用户，参见
https://github.com/HDCodePractice/chstockbot/issues/16

2021-06-06 11:25 UTC, hdcola commented on cmdproc/sendxyh.py
> +spy_200d = df_spy.loc[:,["Close"]].tail(200)["Close"].mean()
有没有发现这段与19~26基本相同，为什么不考虑整一个函数呢？ :)

2021-06-06 11:25 UTC, hdcola commented on cmdproc/sendxyh.py
> +print(market_brief)
哈哈，为什么没有发送消息到一个chatid的东西？ :)

2021-06-06 12:09 UTC, hdcola approved these changes

2021-06-06 12:09 UTC, hdcola commented on cmdproc/sendxyh.py
> +spy_13d = df_spy.loc[:,["Close"]].tail(13)["Close"].mean()
为啥不先tail再切列？这个方式看的我有点晕了都～

2021-06-06 13:13 UTC, stephenzhu01 commented on cmdproc/sendxyh.py
> +spy_200d = df_spy.loc[:,["Close"]].tail(200)["Close"].mean()
呃，确实可以。写的时候第一反应是‘哈，直接copy 改几个字母就好’。😓

2021-06-06 13:16 UTC, stephenzhu01 commented on cmdproc/sendxyh.py
> +spy_13d = df_spy.loc[:,["Close"]].tail(13)["Close"].mean()
> 为啥不先tail再切列？这个方式看的我有点晕了都～

呃，这一块应该再review一下的。

2021-06-13 02:40 UTC, closed without merging