Ben's homework and question
hdcola/chstockbot pull request #19
Opened 2021-06-05 19:24 UTC by lben1216

房东哥您好， 我刚刚提交了一个pull request，可以麻烦您帮我看一下是否哪里需要改进吗？ 非常感谢！ 

另外关于计算周期均价 我有一些问题：
1. 在我的代码中，均价是通过计算过去13/50/200周（包括当天的价格）的收盘价的平均值来得到的， 所以我的定时消息是在盘后16:05发出来的。那如果我的定时消息的时间设在了每天中午12:00 pm， 那当天的收盘价是无法被读取的，在这种情况下，我需要把今天的数据从我的数据组中移除 ，然后计算之前的收盘价的平均值吗？ 还是我需要取得当时12:00pm的即时股票价格，并用这个价格来当作当天的收盘价，再计算平均值呢？

2. 关于我们计算出来的数据和其他网站的数据不同，您有提到说关于有些网站会使用加权平均值来计算均价， 您觉得这种方式会给出更准确的趋势吗？ 使用只计算收盘价的均价或者使用加权均价在对于股市走势的预测上会对用户的判断造成影响吗？

3. 关于周期均价的计算，有没有一个大家公认的计算方式？ 还是大家都有自己的方法？ 如何才能最准确的计算出均价呢？

谢谢房东哥：）

2021-06-06 11:31 UTC, hdcola commented
> 在我的代码中，均价是通过计算过去13/50/200周（包括当天的价格）的收盘价的平均值来得到的， 所以我的定时消息是在盘后16:05发出来的。那如果我的定时消息的时间设在了每天中午12:00 pm， 那当天的收盘价是无法被读取的，在这种情况下，我需要把今天的数据从我的数据组中移除 ，然后计算之前的收盘价的平均值吗？ 还是我需要取得当时12:00pm的即时股票价格，并用这个价格来当作当天的收盘价，再计算平均值呢？

盘中是以当前价格来计算均线价格的。所以你会发现在盘中波动时均线也在不断的波动，这就是为什么有时你看到一个方向，但是随着时间的推移，方向走反的原因。

> 关于我们计算出来的数据和其他网站的数据不同，您有提到说关于有些网站会使用加权平均值来计算均价， 您觉得这种方式会给出更准确的趋势吗？ 使用只计算收盘价的均价或者使用加权均价在对于股市走势的预测上会对用户的判断造成影响吗？

看大家的使用习惯了，如果是熟悉的人，使用自己熟悉的方法就好了。以xyh的目的，我认为完全不是为了判断走势，所以不重要。

> 关于周期均价的计算，有没有一个大家公认的计算方式？ 还是大家都有自己的方法？ 如何才能最准确的计算出均价呢？

移动平均线，Moving Average，简称MA，MA是用统计分析的方法，将一定时期内的证券价格（指数）加以平均，并把不同时间的平均值连接起来，形成一根MA，用以观察证券价格变动趋势的一种技术指标。

N日移动平均线=N日收市价之和/N

2021-06-06 11:44 UTC, hdcola requested changes
1.周期计算变为了周计算，应该为周期计算
2.计算指票数量等于了请求服务器的数量，应该尽少的向服务器请求数据

2021-06-06 11:44 UTC, hdcola commented on sendxyh.py
> +    response = requests.get(url,params=data)
好粗暴，如果我们要发markup类或带有图片之类的消息时，这个会烦恼。但是只发送文字消息到还不错～

2021-06-06 11:44 UTC, hdcola commented on sendxyh.py
> +    start = datetime.date.today() - datetime.timedelta(weeks=week)
为什么start要-week呢？我没太想明白。当前价格都是一周或13周前的？哈哈，我明白了，你把周期理解为周了。😅

2021-06-06 11:44 UTC, hdcola commented on sendxyh.py
> +    print(f"""avg open price: {avg_open_price:.2f}, avg close price: {avg_close_price:.2f}, avg high price: {avg_high_price:.2f},avg low price: {avg_low_price:.2f}""")
debug语句在提交时应该注释掉

2021-06-06 11:44 UTC, hdcola commented on sendxyh.py
> +    spy_200 = cal_avg_price('spy', 200)
这个cal_avg_price每次会请求一次服务器，如果计算数量大一点点，比如100个指标，可能服务器就会把你做为DOS攻击给ban了。所以应该考虑让一次对服务器的请求得回来的数据量被充分的使用。这里qqq和spy两个票很多个数据的计算应该只请求两次，在请求回来的数据上进行处理。

2021-06-07 02:02 UTC, lben1216 commented on sendxyh.py
> +    response = requests.get(url,params=data)
已修改，使用bot来发送信息

2021-06-07 02:02 UTC, lben1216 commented on sendxyh.py
> +    start = datetime.date.today() - datetime.timedelta(weeks=week)
计算方式已进行修改 ：）

2021-06-07 02:03 UTC, lben1216 commented on sendxyh.py
> +    print(f"""avg open price: {avg_open_price:.2f}, avg close price: {avg_close_price:.2f}, avg high price: {avg_high_price:.2f},avg low price: {avg_low_price:.2f}""")
debug语句已经被移除

2021-06-07 02:03 UTC, lben1216 commented on sendxyh.py
> +    spy_200 = cal_avg_price('spy', 200)
读取数据方式已进行修改，一只股票只进行一次服务器的请求

2021-06-07 02:06 UTC, lben1216 commented
房东哥您好！ 我又来啦！ 哈哈！ 根据您的建议 我又重新写了代码，可以麻烦您再看一下吗？ 非常感谢～

2021-06-07 02:25 UTC, closed without merging