Update： 均价计算 作业
hdcola/chstockbot pull request #23
Opened 2021-06-07 02:26 UTC by lben1216

房东哥您好！ 我又来啦！ 哈哈！ 根据您的建议 我又重新写了代码，可以麻烦您再看一下吗？ 非常感谢～

2021-06-07 21:33 UTC, hdcola approved these changes
基础部分都没问题，只有一点建议了

2021-06-07 21:33 UTC, hdcola commented on sendxyh.py
> +        message += f"""failed to fetch/calculate data due to {e}"""
这里的处理其实可以有一点点技巧，可以自己抛出异常来完成这里。参看
https://www.w3school.com.cn/python/python_try_except.asp
我们的处理方法一般可以这样：
比如yahoo或stooq出问题，得不到数据，这时raise出一个异常，在调用这个函数时，如果得到了这个异常，那么可以考虑向一个admingroup发出错误提示让管理员去做做处理。

2021-06-13 13:08 UTC, lben1216 commented on sendxyh.py
> +        message += f"""failed to fetch/calculate data due to {e}"""
谢谢房东哥， 我在代码里重新写了try exception/raise exception，但是总觉得怪怪的，还请房东哥指导

2021-06-13 13:30 UTC, hdcola requested changes
记得要try啊

2021-06-13 13:30 UTC, hdcola commented on sendxyh.py
> +    if Exception or DataError:
哈哈，try啊～

2021-06-13 13:30 UTC, hdcola commented on sendxyh.py
> +        for ma in ma:
最好不要使用相同的变量名，这时的ma是一个list还是一个int，会让人困惑的

2021-06-13 13:30 UTC, hdcola commented on sendxyh.py
> +    if Exception or DataError:
你可以try别人的raise的Exception，也可以try自己的Exception啊

2021-06-13 15:49 UTC, hdcola requested changes

2021-06-13 15:49 UTC, hdcola commented on sendxyh.py
> +        raise DataError
自己创建一个 Error   EmptyDateError
raise EmptyDataError(f"{symble} data is empty")

2021-06-13 15:49 UTC, hdcola commented on sendxyh.py
> +    bot.send_message(chat_id=group_id,text=out_message)
except Exception 后，如果再给group_id send_message感觉上会有问题，因为这时可能什么数据都取不到了。

2021-06-13 16:01 UTC, closed without merging