作业 -- 增加新功能
hdcola/chstockbot pull request #29
Opened 2021-06-18 19:48 UTC by lben1216

房东哥好！ 这是我这周的作业， 用了比较粗暴的方法来实现您要求的功能，还请您帮忙看一下 ：） 非常感谢！

1. 在计算均价的函数中加入ds变量
2. 对数据重新排序，使数据按日期前后排列
3. 增加checkpoint来判断今天是否开盘
4. 增加均价和收盘价的比较并加入红绿灯
5. 当天不发出天相时，向admin group报告
6. 部分格式修改

2021-06-18 23:33 UTC, hdcola requested changes
出错的情况下不应该把出错消息发给用户，应该发给管理组

2021-06-18 23:33 UTC, hdcola commented on sendxyh.py
> +ds = 'yahoo'
这里可以看 #28 @stephenzhu01 让我更有了灵感。设置一个 ['stooq','yahoo'] 这样的一个list，按第一个、第二个顺序来，第一个挂了，去找第二个。不一定写啊，咱们可以做为下个需求，或是我们明天上课时我们来讨论下下怎么实现。 :)

2021-06-18 23:33 UTC, hdcola commented on sendxyh.py
> +            return f"{ds} 没找到今天的数据，看来要不没开市，要不没收盘，要不数据还没更新，请尝试其他数据源， 当前数据源不发出天相信息\n"
这个就会把出问题的情况发给用户，而不是管理员。感觉上会有更好的处理方法。

2021-06-18 23:39 UTC, lben1216 commented on sendxyh.py
> +ds = 'yahoo'
谢谢房东哥， 对的， 我觉得这样会让用户体验更友好一点，也不需要手动更改数据源。

2021-06-18 23:41 UTC, lben1216 commented on sendxyh.py
> +            return f"{ds} 没找到今天的数据，看来要不没开市，要不没收盘，要不数据还没更新，请尝试其他数据源， 当前数据源不发出天相信息\n"
谢谢房东哥， 我本来是想抛出一个异常，但我觉得这个判断并不算是一个bug或者error，所以我还是用了return一个message， 这个信息会发给admingroup， 我再想想看怎么修改它。谢谢房东哥！

2021-06-20 05:44 UTC, lben1216 commented
重新提交新的pull request，关闭当前request

2021-06-20 05:44 UTC, closed without merging